language: go

os:
  - linux
  - osx

go:
  - 1.7
before_install:
    - go get github.com/valyala/fasttemplate


script:
    - ./tests/functional-test.sh
    - cd process && go test
      #    - ORDERED="-o" ./tests/functional-test.sh

